import DEFAULT_CATEGORIES from './default_categories.js'

/**
 * default_items.js
 * This file contains the default items that can be added to lists in our app
 */

const DEFAULT_ITEMS = [
  //----- Category 1 - Alcoholic drinks -----//
  { id: 1, en: 'Ale',                           es: 'Ale',                              categoryId: 1 },
  { id: 1, en: 'Apple cider',                   es: '',                                 categoryId: 1 },
  { id: 1, en: 'Baileys',                       es: 'Baileys',                          categoryId: 1 },
  { id: 2, en: 'Beer',                          es: 'Cerveza',                          categoryId: 1 },
  { id: 3, en: 'Brandy',                        es: 'Brandy',                           categoryId: 1 },
  { id: 1, en: 'Champagne',                     es: 'Champagne',                        categoryId: 1 },
  { id: 1, en: 'Cider',                         es: 'Sidra',                            categoryId: 1 },
  { id: 1, en: 'Cognac',                        es: 'Coñac',                            categoryId: 1 },
  { id: 1, en: 'Gin',                           es: 'Ginebra',                          categoryId: 1 },
  { id: 1, en: 'Ginger ale',                    es: 'Ginger ale',                       categoryId: 1 },
  { id: 1, en: 'Lager',                         es: 'Lager',                            categoryId: 1 },
  { id: 1, en: 'Liqueur',                       es: 'Licor',                            categoryId: 1 },
  { id: 1, en: 'Martini',                       es: 'Martini',                          categoryId: 1 },
  { id: 1, en: 'Red wine',                      es: 'Vino tinto',                       categoryId: 1 },
  { id: 1, en: 'Rosé wine',                     es: 'Vino rosado',                      categoryId: 1 },
  { id: 1, en: 'Rum',                           es: 'Ron',                              categoryId: 1 },
  { id: 1, en: 'Sparkling wine',                es: 'Vino espumoso',                    categoryId: 1 },
  { id: 1, en: 'Tequia',                        es: 'Tequila',                          categoryId: 1 },
  { id: 1, en: 'Vodka',                         es: 'Vodka',                            categoryId: 1 },
  { id: 1, en: 'Wheat beer',                    es: 'Cerveza de trigo',                 categoryId: 1 },
  { id: 1, en: 'Whiskey',                       es: '',                                 categoryId: 1 },
  { id: 1, en: 'Whisky',                        es: 'Whisky',                           categoryId: 1 },
  { id: 1, en: 'White wine',                    es: 'Vino blanco',                      categoryId: 1 },
  { id: 1, en: 'Wine',                          es: 'Vino',                             categoryId: 1 },
  { id: 1, en: '',                              es: 'Orujo',                            categoryId: 1 },
  { id: 1, en: '',                              es: 'Crema de orujo',                   categoryId: 1 },
  { id: 1, en: '',                              es: 'Aguardiente',                      categoryId: 1 },
  { id: 1, en: '',                              es: 'Licor de hierbas',                 categoryId: 1 },

  //----- Category 2 - Baby products -----//
  { id: 1, en: 'Baby food',                     es: 'Comida para bebés',                categoryId: 2 },
  { id: 1, en: '',                              es: 'Potito',                           categoryId: 2 },
  { id: 1, en: 'Diapers',                       es: 'Pañales',                          categoryId: 2 },
  { id: 1, en: 'Feeding bottle',                es: 'Biberón',                          categoryId: 2 },
  { id: 1, en: 'Pacifier',                      es: 'Chupete',                          categoryId: 2 },

  //----- Category 3 - Bakery -----//
  { id: 1, en: 'Apple pie',                     es: 'Tarta de manzana',                 categoryId: 3 },
  { id: 1, en: 'Bagel',                         es: 'Rosca',                            categoryId: 3 },
  { id: 1, en: 'Baguette',                      es: 'Baguette',                         categoryId: 3 },
  { id: 1, en: 'Birthday cake',                 es: 'Tarta de cumpleaños',              categoryId: 3 },
  { id: 1, en: 'Bread',                         es: 'Pan',                              categoryId: 3 },
  { id: 1, en: 'Breadcrumbs',                   es: 'Pan rallado',                      categoryId: 3 },
  { id: 1, en: 'Brownie',                       es: 'Brownie',                          categoryId: 3 },
  { id: 1, en: 'Bun',                           es: 'Bollo',                            categoryId: 3 },
  { id: 1, en: 'Cake',                          es: 'Tarta',                            categoryId: 3 },
  { id: 1, en: 'Cheesecake',                    es: 'Tarta de queso',                   categoryId: 3 },
  { id: 1, en: 'Croissants',                    es: 'Croissants',                       categoryId: 3 },
  { id: 1, en: '',                              es: 'Cruasanes',                        categoryId: 3 },
  { id: 1, en: 'Croutons',                      es: 'Picatostes',                       categoryId: 3 },
  { id: 1, en: 'Cupcakes',                      es: 'Cupcakes',                         categoryId: 3 },
  { id: 1, en: 'Donuts',                        es: 'Donuts',                           categoryId: 3 },
  { id: 1, en: 'Dough',                         es: 'Masa',                             categoryId: 3 },
  { id: 1, en: 'Flour',                         es: 'Harina',                           categoryId: 3 },
  { id: 1, en: 'Garlic bread',                  es: 'Pan de ajo',                       categoryId: 3 },
  { id: 1, en: 'Flour',                         es: 'Harina',                           categoryId: 3 },
  { id: 1, en: 'Hamburger buns',                es: 'Pan de hamburguesa',               categoryId: 3 },
  { id: 1, en: 'Hot dog buns',                  es: 'Pan de perrito caliente',          categoryId: 3 },
  { id: 1, en: 'Muffins',                       es: 'Magdalenas',                       categoryId: 3 },
  { id: 1, en: 'Pie',                           es: 'Empanada',                         categoryId: 3 },
  { id: 1, en: 'Pita bread',                    es: 'Pan de pita',                      categoryId: 3 },
  { id: 1, en: 'Matzos',                        es: 'Matzos',                           categoryId: 3 },
  { id: 1, en: 'Taco shells',                   es: '',                                 categoryId: 3 },
  { id: 1, en: 'Tortillas',                     es: 'Tortillas mexicanas',              categoryId: 3 },
  { id: 1, en: 'Wheat tortillas',               es: 'Tortillas de trigo',               categoryId: 3 },
  { id: 1, en: 'Corn tortillas',                es: 'Tortillas de maíz',                categoryId: 3 },
  { id: 1, en: 'Tiramisu',                      es: 'Tiramisú',                         categoryId: 3 },
  { id: 1, en: '',                              es: 'Pan Bimbo',                        categoryId: 3 },
  { id: 1, en: 'Sliced bread',                  es: 'Pan de molde',                     categoryId: 3 },
  { id: 1, en: 'Wholemeal bread',               es: 'Pan integral',                     categoryId: 3 },

  //----- Category 4 - Canned food -----//
  { id: 1, en: 'Canned tuna',                   es: 'Atún en lata',                     categoryId: 1 },
  { id: 1, en: 'Tuna in oil',                   es: 'Atún en aceite',                   categoryId: 1 },
  { id: 1, en: '',               es: 'Tortillas de trigo',               categoryId: 1 },

  //----- Category 5 - Cleaning -----//
  { id: 1, en: 'Air freshener',                 es: 'Ambientador',                      categoryId: 1 },
  { id: 1, en: 'Bags',                          es: 'Bolsas',                           categoryId: 1 },

  //----- Category 6 - Clothes -----//
  { id: 1, en: 'Blouse',                        es: 'Blusa',                            categoryId: 6 },
  { id: 1, en: 'Boots',                         es: 'Botas',                            categoryId: 6 },
  { id: 1, en: 'Cap',                           es: 'Gorra',                            categoryId: 6 },
  { id: 1, en: 'Coat',                          es: 'Abrigo',                           categoryId: 6 },
  { id: 1, en: 'Flip-flops',                    es: 'Chanclas',                         categoryId: 6 },
  { id: 1, en: 'Thongs',                        es: 'Chancleta',                        categoryId: 6 },
  { id: 1, en: 'Gloves',                        es: 'Guantes',                          categoryId: 6 },
  { id: 1, en: 'Jacket',                        es: 'Chaqueta',                         categoryId: 6 },
  { id: 1, en: 'Jeans',                         es: 'Jeans',                            categoryId: 6 },
  { id: 1, en: '',                              es: 'Pantalones vaqueros',              categoryId: 6 },
  { id: 1, en: 'Leggins',                       es: 'Leggins',                          categoryId: 6 },
  { id: 1, en: 'Stockings',                     es: 'Medias',                           categoryId: 6 },
  { id: 1, en: 'Scarf',                         es: 'Bufanda',                          categoryId: 6 },
  { id: 1, en: 'Shirt',                         es: 'Camisa',                           categoryId: 6 },
  { id: 1, en: 'Shoes',                         es: 'Zapatos',                          categoryId: 6 },
  { id: 1, en: 'Slippers',                      es: 'Zapatillas de andar por casa',     categoryId: 6 },
  { id: 1, en: 'Socks',                         es: 'Calcetines',                       categoryId: 6 },
  { id: 1, en: 'Sweater',                       es: 'Suéter',                           categoryId: 6 },
  { id: 1, en: 'Jersey',                        es: 'Jersey',                           categoryId: 6 },
  { id: 1, en: 'Pullover',                      es: 'Pulóver',                          categoryId: 6 },
  { id: 1, en: 'Jumper',                        es: '',                                 categoryId: 6 },
  { id: 1, en: 'Sweatshirt',                    es: '',                                 categoryId: 6 },
  { id: 1, en: 'Hoodie',                        es: 'Sudadera',                         categoryId: 6 },
  { id: 1, en: 'Trunks',                        es: 'Bañador',                          categoryId: 6 },
  { id: 1, en: 'T-shirt',                       es: 'Camiseta',                         categoryId: 6 },
  { id: 1, en: 'Underpants',                    es: 'Calzoncillos',                     categoryId: 6 },
  { id: 1, en: 'Underwear',                     es: 'Ropa interior',                    categoryId: 6 },
  { id: 1, en: 'Bra',                           es: 'Sujetador',                        categoryId: 6 },
  { id: 1, en: 'Panties',                       es: 'Pantis',                           categoryId: 6 },
  { id: 1, en: 'Knickers',                      es: 'Bragas',                           categoryId: 6 },
  { id: 1, en: 'Hat',                           es: 'Sombrero',                         categoryId: 6 },
  { id: 1, en: 'Costume',                       es: 'Disfraz',                          categoryId: 6 },

  //----- Category 7 - Drinks -----//
  { id: 1, en: '7 Up',                          es: '7 Up',                             categoryId: 1 },
  { id: 1, en: 'Apple juice',                   es: 'Zumo de manzana',                  categoryId: 1 },
  { id: 1, en: 'Coca-Cola',                     es: 'Coca-Cola',                        categoryId: 1 },
  { id: 1, en: 'Diet coke',                     es: 'Coca-Cola light',                  categoryId: 1 },
  { id: 1, en: 'Coke zero',                     es: 'Coca-Cola zero',                   categoryId: 1 },
  { id: 1, en: 'Coke',                          es: '',                                 categoryId: 1 },
  { id: 1, en: 'Coconut water',                 es: 'Agua de coco',                     categoryId: 1 },
  { id: 1, en: 'Dr Pepper',                     es: 'Dr Pepper',                        categoryId: 1 },
  { id: 1, en: 'Juice',                         es: 'Zumo',                             categoryId: 1 },
  { id: 1, en: 'Lemon juice',                   es: 'Zumo de limón',                    categoryId: 1 },
  { id: 1, en: 'Lemonade',                      es: 'Limonada',                         categoryId: 1 },
  { id: 1, en: 'Lime juice',                    es: 'Zumo de lima',                     categoryId: 1 },
  { id: 1, en: 'Orange juice',                  es: 'Zumo de naranja',                  categoryId: 1 },
  { id: 1, en: 'Pepsi',                         es: 'Pepsi',                            categoryId: 1 },
  { id: 1, en: 'Schweppes',                     es: 'Schweppes',                        categoryId: 1 },
  { id: 1, en: 'Soda water',                    es: 'Agua con gas',                     categoryId: 1 },
  { id: 1, en: 'Sparkling water',               es: '',                                 categoryId: 1 },
  { id: 1, en: 'Sprite',                        es: 'Sprite',                           categoryId: 1 },
  { id: 1, en: 'Tomato juice',                  es: 'Zumo de tomate',                   categoryId: 1 },
  { id: 1, en: 'Tonic water',                   es: 'Tónica',                           categoryId: 1 },
  { id: 1, en: 'Aquarius',                      es: 'Aquarius',                         categoryId: 1 },
  { id: 1, en: 'Red Bull',                      es: 'Red Bull',                         categoryId: 1 },

  //----- Category 8 - Eggs & dairy -----//
  { id: 1, en: 'Activia',                       es: 'Activia',                          categoryId: 1 },
  { id: 1, en: 'Babybel',                       es: 'Babybel',                          categoryId: 1 },
  { id: 1, en: 'Blue cheese',                   es: 'Queso azul',                       categoryId: 1 },
  { id: 1, en: 'Boiled eggs',                   es: 'Huevos cocidos',                   categoryId: 1 },
  { id: 1, en: 'Brie cheese',                   es: 'Queso brie',                       categoryId: 1 },
  { id: 1, en: 'Butterscotch',                  es: '',                                 categoryId: 1 },
  { id: 1, en: 'Camembert cheese',              es: 'Queso camembert',                  categoryId: 1 },
  { id: 1, en: 'Cheddar cheese',                es: 'Queso cheddar',                    categoryId: 1 },
  { id: 1, en: 'Cottage cheese',                es: 'Requesón',                         categoryId: 1 },
  { id: 1, en: 'Philadelphia',                  es: 'Philadelphia',                     categoryId: 1 },
  { id: 1, en: 'Condensed milk',                es: 'Leche condensada',                 categoryId: 1 },
  { id: 1, en: 'Milkshake',                     es: 'Batido',                           categoryId: 1 },
  { id: 1, en: 'Curd',                          es: 'Cuajada',                          categoryId: 1 },
  { id: 1, en: 'Cream',                         es: 'Nata',                             categoryId: 1 },
  { id: 1, en: 'Whipped cream',                 es: 'Nata montada',                     categoryId: 1 },
  { id: 1, en: 'Whipping cream',                es: 'Nata para montar',                 categoryId: 1 },
  { id: 1, en: 'Half & Half',                   es: 'Nata para cocinar',                categoryId: 1 },
  { id: 1, en: 'Edam cheese',                   es: 'Queso edam',                       categoryId: 1 },
  { id: 1, en: 'Eggs',                          es: 'Huevos',                           categoryId: 1 },
  { id: 1, en: 'Egg whites',                    es: 'Claras de huevo',                  categoryId: 1 },
  { id: 1, en: 'Feta cheese',                   es: 'Queso feta',                       categoryId: 1 },
  { id: 1, en: 'Fruit yogurt',                  es: 'Yogur de frutas',                  categoryId: 1 },
  { id: 1, en: 'Goat cheese',                   es: 'Queso de cabra',                   categoryId: 1 },
  { id: 1, en: 'Goat milk',                     es: 'Leche de cabra',                   categoryId: 1 },
  { id: 1, en: 'Gorgonzola cheese',             es: 'Queso gorgonzola',                 categoryId: 1 },
  { id: 1, en: 'Gouda cheese',                  es: 'Queso gouda',                      categoryId: 1 },
  { id: 1, en: 'Grated cheese',                 es: 'Queso rallado',                    categoryId: 1 },
  { id: 1, en: 'Greek yogurt',                  es: 'Yogur griego',                     categoryId: 1 },
  { id: 1, en: 'Mascarpone cheese',             es: 'Queso mascarpone',                 categoryId: 1 },
  { id: 1, en: 'Milk',                          es: 'Leche',                            categoryId: 1 },
  { id: 1, en: 'Mozzarella cheese',             es: 'Queso mozzarella',                 categoryId: 1 },
  { id: 1, en: 'Natural yogurt',                es: 'Yogur natural',                    categoryId: 1 },
  { id: 1, en: 'Parmesan cheese',               es: 'Queso parmesano',                  categoryId: 1 },
  { id: 1, en: 'Provolone cheese',              es: 'Queso provolone',                  categoryId: 1 },
  { id: 1, en: 'Rice pudding',                  es: 'Arroz con leche',                  categoryId: 1 },
  { id: 1, en: 'Ricotta cheese',                es: 'Queso ricotta',                    categoryId: 1 },
  { id: 1, en: 'Smoothie',                      es: 'Smoothie',                         categoryId: 1 },
  { id: 1, en: 'Sour cream',                    es: 'Batido',                           categoryId: 1 },
  { id: 1, en: 'Cheese',                        es: 'Queso',                            categoryId: 1 },
  { id: 1, en: 'Manchego cheese',               es: 'Queso machego',                    categoryId: 1 },
  { id: 1, en: 'Cured cheese',                  es: 'Queso curado',                     categoryId: 1 },
  { id: 1, en: 'Smoked cheese',                 es: 'Queso ahumado',                    categoryId: 1 },
  { id: 1, en: 'Almond milk',                   es: 'Leche de almendras',               categoryId: 1 },
  { id: 1, en: 'Rice milk',                     es: 'Leche de arroz',                   categoryId: 1 },
  { id: 1, en: 'Soy milk',                      es: 'Leche de soja',                    categoryId: 1 },
  { id: 1, en: 'Coconut milk',                  es: 'Leche de coco',                    categoryId: 1 },

  //----- Category 9 - Fish & seafood -----//
  { id: 1, en: 'Anchovies',                     es: 'Anchoas',                          categoryId: 1 },
  { id: 1, en: 'Brisling',                      es: 'Espadín',                          categoryId: 1 },
  { id: 1, en: 'Carp',                          es: 'Carpa',                            categoryId: 1 },
  { id: 1, en: 'Catfish',                       es: 'Bagre',                            categoryId: 1 },
  { id: 1, en: 'Clams',                         es: 'Almejas',                          categoryId: 1 },
  { id: 1, en: 'Cod',                           es: 'Bacalao',                          categoryId: 1 },
  { id: 1, en: 'Crab fingers',                  es: 'Patas de cangrejo',                categoryId: 1 },
  { id: 1, en: 'Crab',                          es: 'Cangrejo',                         categoryId: 1 },
  { id: 1, en: 'Fish',                          es: 'Pescado',                          categoryId: 1 },
  { id: 1, en: 'Fish fingers',                  es: 'Palitos de pescado',               categoryId: 1 },
  { id: 1, en: 'Hake',                          es: 'Merluza',                          categoryId: 1 },
  { id: 1, en: 'Halibut',                       es: 'Platija',                          categoryId: 1 },
  { id: 1, en: 'Herring',                       es: 'Arenques',                         categoryId: 1 },
  { id: 1, en: 'Lobster',                       es: 'Langosta',                         categoryId: 1 },
  { id: 1, en: 'Mussels',                       es: 'Mejillones',                       categoryId: 1 },
  { id: 1, en: 'Oysters',                       es: 'Ostras',                           categoryId: 1 },
  { id: 1, en: 'Perch',                         es: 'Perca',                            categoryId: 1 },
  { id: 1, en: 'Prawns',                        es: 'Gambas',                           categoryId: 1 },
  { id: 1, en: 'Shrimps',                       es: 'Langostinos',                      categoryId: 1 },
  { id: 1, en: 'Salmon',                        es: 'Salmón',                           categoryId: 1 },
  { id: 1, en: 'Seafood',                       es: 'Marisco',                          categoryId: 1 },
  { id: 1, en: 'Sardines',                      es: 'Sardinas',                         categoryId: 1 },
  { id: 1, en: 'Scallops',                      es: 'Vieiras',                          categoryId: 1 },
  { id: 1, en: 'Smoked salmon',                 es: 'Salmón ahumado',                   categoryId: 1 },
  { id: 1, en: 'Swordfish',                     es: 'Pez espada',                       categoryId: 1 },
  { id: 1, en: '',                              es: 'Emperador',                        categoryId: 1 },
  { id: 1, en: 'Tilapia',                       es: 'Tilapia',                          categoryId: 1 },
  { id: 1, en: 'Trout',                         es: 'Trucha',                           categoryId: 1 },
  { id: 1, en: 'Tuna',                          es: 'Atún',                             categoryId: 1 },
  { id: 1, en: '',                              es: 'Bonito',                           categoryId: 1 },

  //----- Category 10 - Frozen food -----//
  { id: 1, en: 'Frozen Fries',                  es: 'Patatas fritas congeladas',        categoryId: 1 },
  { id: 1, en: 'Puff Pastry',                   es: 'Hojaldre',                         categoryId: 1 },
  { id: 1, en: 'Filo pastry',                   es: 'Hojaldre filo',                    categoryId: 1 },
  { id: 1, en: 'Frozen vegetables',             es: 'Verduras congeladas',              categoryId: 1 },
  { id: 1, en: 'Frozen pizza',                  es: 'Pizza congelada',                  categoryId: 1 },
  { id: 1, en: 'Frozen lasagna',                es: 'Lasaña congelada',                 categoryId: 1 },
  { id: 1, en: 'Frozen spinach',                es: 'Espinacas congeladas',             categoryId: 1 },
  { id: 1, en: 'Frozen carrots',                es: 'Zanahorias congeladas',            categoryId: 1 },
  { id: 1, en: 'Frozen peas',                   es: 'Guisantes congelados',             categoryId: 1 },
  { id: 1, en: 'Ice cream',                     es: 'Helado',                           categoryId: 1 },
  { id: 1, en: 'Milk',                          es: 'Leche',                            categoryId: 1 },

  //----- Category 11 - Fruit & vegetables -----//
  { id: 1, en: 'Chamomile tea',                 es: 'Manzanilla',                       categoryId: 1 },
  { id: 1, en: 'Coffee',                        es: 'Café',                             categoryId: 1 },
  { id: 1, en: 'Green tea',                     es: 'Té verde',                         categoryId: 1 },
  { id: 1, en: 'Tea',                           es: 'Té',                               categoryId: 1 },

  //----- Category 12 - Grains, beans & pasta -----//
  { id: 1, en: 'Barley',                        es: 'Cebada',                           categoryId: 1 },
  { id: 1, en: 'Basmati rice',                  es: 'Arroz basmati',                    categoryId: 1 },
  { id: 1, en: 'Black beans',                   es: 'Judías negras',                    categoryId: 1 },
  { id: 1, en: '',                              es: 'Frijoles negros',                  categoryId: 1 },
  { id: 1, en: 'All-Bran',                      es: 'All-Bran',                         categoryId: 1 },
  { id: 1, en: 'Brown rice',                    es: 'Arroz integral',                   categoryId: 1 },
  { id: 1, en: 'Cereal',                        es: 'Cereales',                         categoryId: 1 },
  { id: 1, en: 'Corn flakes',                   es: 'Corn flakes',                      categoryId: 1 },
  { id: 1, en: 'Couscous',                      es: 'Cuscús',                           categoryId: 1 },
  { id: 1, en: 'Flour',                         es: 'Harina',                           categoryId: 1 },
  { id: 1, en: 'Granola',                       es: 'Granola',                          categoryId: 1 },
  { id: 1, en: 'Lasagna sheets',                es: 'Pasta para lasaña',                categoryId: 1 },
  { id: 1, en: 'Lentils',                       es: 'Lentejas',                         categoryId: 1 },
  { id: 1, en: 'Muesli',                        es: 'Muesli',                           categoryId: 1 },
  { id: 1, en: 'Oatmeal',                       es: 'Gachas',                           categoryId: 1 },
  { id: 1, en: 'Pasta',                         es: 'Pasta',                            categoryId: 1 },
  { id: 1, en: 'Penne',                         es: 'Macarrones',                       categoryId: 1 },
  { id: 1, en: 'Quinoa',                        es: 'Quinoa',                           categoryId: 1 },
  { id: 1, en: 'Rice',                          es: 'Arroz',                            categoryId: 1 },
  { id: 1, en: 'Rotini',                        es: 'Espirales de pasta',               categoryId: 1 },
  { id: 1, en: 'Spaghetti',                     es: 'Espaguetis',                       categoryId: 1 },
  { id: 1, en: 'Tortellini',                    es: 'Tortellini',                       categoryId: 1 },
  { id: 1, en: 'Whole grain pasta',             es: 'Pasta integral',                   categoryId: 1 },
  { id: 1, en: 'Beans',                         es: 'Judías',                           categoryId: 1 },
  { id: 1, en: '',                              es: 'Habas',                            categoryId: 1 },
  { id: 1, en: '',                              es: 'Alubias',                          categoryId: 1 },
  { id: 1, en: '',                              es: 'Frijoles',                         categoryId: 1 },
  { id: 1, en: 'White beans',                   es: 'Judías blancas',                   categoryId: 1 },
  { id: 1, en: 'Green beans',                   es: 'Judías verdes',                    categoryId: 1 },
  { id: 1, en: 'Chickpeas',                     es: 'Garbanzos',                        categoryId: 1 },
  { id: 1, en: 'Guisantes',                     es: 'Peas',                             categoryId: 1 },
  { id: 1, en: 'Soy beans',                     es: 'Judías de soja',                   categoryId: 1 },

  //----- Category 13 - Home appliances -----//
  { id: 1, en: 'Batteries',                     es: 'Pilas',                            categoryId: 1 },

  //----- Category 14 - Hygiene & wellbeing -----//
  { id: 1, en: '',                              es: 'Loción para después de afeitar',   categoryId: 1 },
  { id: 1, en: 'After-shave',                   es: 'After shave',                      categoryId: 1 },
  { id: 1, en: 'After-sun',                     es: 'After-sun',                        categoryId: 1 },
  { id: 1, en: 'Bath gel',                      es: 'Gel de baño',                      categoryId: 1 },
  { id: 1, en: 'Bath salts',                    es: 'Sales de baño',                    categoryId: 1 },
  { id: 1, en: 'Cleanser',                      es: 'Desmaquillador',                   categoryId: 1 },
  { id: 1, en: 'Conditioner',                   es: 'Acondicionador',                   categoryId: 1 },
  { id: 1, en: 'Deodorant',                     es: 'Desodorante',                      categoryId: 1 },
  { id: 1, en: 'Floss',                         es: 'Hilo dental',                      categoryId: 1 },
  { id: 1, en: 'Lotion',                        es: 'Crema',                            categoryId: 1 },
  { id: 1, en: 'Hair dye',                      es: 'Tinte',                            categoryId: 1 },
  { id: 1, en: 'Lip balm',                      es: 'Protector labial',                 categoryId: 1 },
  { id: 1, en: 'Lipstick',                      es: 'Pintalabios',                      categoryId: 1 },
  { id: 1, en: 'Make-up remover',               es: '',                                 categoryId: 1 },
  { id: 1, en: 'Mascara',                       es: 'Rímel',                            categoryId: 1 },
  { id: 1, en: 'Mouthwash',                     es: 'Colutorio',                        categoryId: 1 },
  { id: 1, en: 'Nail polish',                   es: 'Pintauñas',                        categoryId: 1 },
  { id: 1, en: 'Nail varnish',                  es: 'Pintura de uñas',                  categoryId: 1 },
  { id: 1, en: 'Nail polish remover',           es: 'Acetona',                          categoryId: 1 },
  { id: 1, en: 'Nail varnish remover',          es: '',                                 categoryId: 1 },
  { id: 1, en: 'Perfume',                       es: 'Perfume',                          categoryId: 1 },
  { id: 1, en: 'Scrub',                         es: 'exfoliante',                       categoryId: 1 },
  { id: 1, en: 'Shampoo',                       es: 'Champú',                           categoryId: 1 },
  { id: 1, en: 'Shaving cream',                 es: 'Crema de afeitar',                 categoryId: 1 },
  { id: 1, en: 'Shaving foam',                  es: 'Espuma de afeitar',                categoryId: 1 },
  { id: 1, en: 'Shower gel',                    es: 'Gel de ducha',                     categoryId: 1 },
  { id: 1, en: 'Soap',                          es: 'Jabón',                            categoryId: 1 },
  { id: 1, en: 'Sunscreen',                     es: 'Crema solar',                      categoryId: 1 },
  { id: 1, en: '',                              es: 'Protector solar',                  categoryId: 1 },

  //----- Category 15 - Kitchen -----//
  { id: 1, en: 'Aluminium foil',                es: 'Papel de aluminio',                categoryId: 1 },
  { id: 1, en: 'Baking paper',                  es: 'Papel de horno',                   categoryId: 1 },
  { id: 1, en: 'Bottle opener',                 es: 'Abrebotellas',                     categoryId: 1 },
  { id: 1, en: 'Bowl',                          es: 'Bol',                              categoryId: 1 },
  { id: 1, en: 'Can opener',                    es: 'Abrelatas',                        categoryId: 1 },
  { id: 1, en: 'Candles',                       es: 'Velas',                            categoryId: 1 },
  { id: 1, en: 'Chopsticks',                    es: 'Palillos chinos',                  categoryId: 1 },
  { id: 1, en: 'Hangers',                       es: 'Perchas',                          categoryId: 1 },
  { id: 1, en: 'Coffee filters',                es: 'Filtros de café',                  categoryId: 1 },
  { id: 1, en: 'Colander',                      es: 'Colador',                          categoryId: 1 },
  { id: 1, en: 'Soap',                          es: 'Jabón',                            categoryId: 1 },

  //----- Category 16 - Meat -----//

  //----- Category 17 - Other -----//

  //----- Category 18 - Pet products -----//

  //----- Category 19 - Ready meals -----//
  { id: 1, en: 'Beef broth',                    es: 'Caldo de res',                     categoryId: 1 },
  { id: 1, en: 'Chicken broth',                 es: 'Caldo de pollo',                   categoryId: 1 },
  { id: 1, en: 'Fish broth',                    es: 'Caldo de pescado',                 categoryId: 1 },
  { id: 1, en: 'Tomato soup',                   es: 'Sopa de tomate',                   categoryId: 1 },
  { id: 1, en: 'Vegetable broth',               es: 'Caldo de verduras',                categoryId: 1 },
  { id: 1, en: 'Tofu',                          es: 'Tofu',                             categoryId: 1 },
  { id: 1, en: 'Veggie sausages',               es: 'Salchichas vegetarianas',          categoryId: 1 },
  { id: 1, en: 'Veggie burgers',                es: 'Hamburguesas vegetarianas',        categoryId: 1 },

  //----- Category 20 - Sauces & oils -----//
  { id: 1, en: 'Balsamic Vinegar',              es: 'Vinagre de Módena',                categoryId: 1 },
  { id: 1, en: 'Honey',                         es: 'Miel',                             categoryId: 1 },
  { id: 1, en: 'Dijon mustard',                 es: 'Mostaza de Dijon',                 categoryId: 1 },
  { id: 1, en: 'Ketchup',                       es: 'Ketchup',                          categoryId: 1 },
  { id: 1, en: 'Maple syrup',                   es: 'Sirope de arce',                   categoryId: 1 },
  { id: 1, en: 'Mayonnaise',                    es: 'Mayonesa',                         categoryId: 1 },
  { id: 1, en: 'Mustard',                       es: 'Mostaza',                          categoryId: 1 },
  { id: 1, en: 'Syrup',                         es: 'Sirope',                           categoryId: 1 },
  { id: 1, en: 'Chocolate syrup',               es: 'Sirope de chocolate',              categoryId: 1 },
  { id: 1, en: 'Strawberry syrup',              es: 'Sirope de fresa',                  categoryId: 1 },
  { id: 1, en: 'Vinegar',                       es: 'Vinagre',                          categoryId: 1 },
  { id: 1, en: 'Vinaigrette',                   es: 'Vinagreta',                        categoryId: 1 },

  //----- Category 21 - Snacks & confectionery -----//

  //----- Category 22 - Spices & condiments -----//
  { id: 1, en: 'Sugar',                         es: 'Azúcar',                             categoryId: 1 },
  { id: 1, en: 'Brown sugar',                   es: 'Azúcar moreno',                      categoryId: 1 },
  { id: 1, en: 'Saccharine',                    es: 'Sacarina',                           categoryId: 1 },
  { id: 1, en: 'Dijon mustard',                 es: 'Mostaza de Dijon',                   categoryId: 1 },
  { id: 1, en: 'Dijon mustard',                 es: 'Mostaza de Dijon',                   categoryId: 1 },
  { id: 1, en: 'Dijon mustard',                 es: 'Mostaza de Dijon',                   categoryId: 1 },
  { id: 1, en: 'Dijon mustard',                 es: 'Mostaza de Dijon',                   categoryId: 1 },

  //----- Category 23 - Spreads -----//
  { id: 1, en: 'Nutella',                       es: 'Nutella',                            categoryId: 1 },
  { id: 1, en: 'Peanut butter',                 es: 'Manteca de cacahuete',               categoryId: 1 },
  { id: 1, en: 'Maple syrup',                   es: 'Sirope de arce',                     categoryId: 1 },
  { id: 1, en: 'Mayonnaise',                    es: 'Mayonesa',                           categoryId: 1 },
  { id: 1, en: 'Butter',                        es: 'Mantequilla',                        categoryId: 1 },
  { id: 1, en: 'Garlic butter',                 es: 'Mantequilla de ajo',                 categoryId: 1 },

]

export default DEFAULT_ITEMS;
